### ISSUE TITLE
Dev mode bug - adding a feature manager block

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/ci.common#261]
Adding a feature manager block to the server.xml after dev mode has started results in an error, when dev mode should trigger installing any newly specified features. 

**Steps to Reproduce**
1. Start dev mode with a `server.xml` that does not have a `featureManager` block.
2. Add a feature manager block, with a feature specified, ie.
```xml
    <featureManager>
        <feature>jakartaee-9.0</feature>
    </featureManager>
```
3. Notice the error in the dev mode console:
```
[INFO] Copied file: /Users/kathrynkodama/devex/sampleProjects/vaccination-demo-app/src/main/liberty/config/server.xml to: /private/var/folders/gr/3p093xzj0f9fj9psx80z_zw00000gn/T/tempConfig18101587657383742248/server.xml
[INFO] Parsing the server file /private/var/folders/gr/3p093xzj0f9fj9psx80z_zw00000gn/T/tempConfig18101587657383742248/server.xml for features and includes.
[INFO] Parsing the server file /private/var/folders/gr/3p093xzj0f9fj9psx80z_zw00000gn/T/tempConfig18101587657383742248/configDropins/overrides/liberty-plugin-variable-config.xml for features and includes.
[ERROR] Could not file process changes for /Users/kathrynkodama/devex/sampleProjects/vaccination-demo-app/src/main/liberty/config/server.xml: null
```
It seems the `server.xml` is not successfully copied over to the `usr/servers` directory. The error message is coming from [DevUtil](https://github.com/OpenLiberty/ci.common/blob/d3df1e454d644a8e86d418c62a700cc2d1e0532b/src/main/java/io/openliberty/tools/common/plugins/util/DevUtil.java#L2795) and the `getServerXmlFeatures` method in [ServerFeatureUtil](https://github.com/OpenLiberty/ci.common/blob/main/src/main/java/io/openliberty/tools/common/plugins/util/ServerFeatureUtil.java#L246)

**Expected Behaviour**
After completing step 2 above, the expected behaviour would be that Liberty installs the corresponding feature.  This would match the behaviour of starting Liberty with `liberty:run` and adding the `featureManager` block in the `usr/server/serverName/server.xml` file.

**Comment by cherylking** [comment]
Closing as this is not reproducible on latest version of the plugins.
