### ISSUE TITLE
maven-artifact should be "provided"

### ISSUE THREAD

**Issue by bmarwell** [OpenLiberty/ci.common#404]
Maven artifact should be "provided".
The version is not synchronized among other projects, e.g. ci.maven. I would recommend to extact its version into a property which can then be consumed by ci.maven.

**Comment by cherylking** [comment]
After further discussion, I think this dependency should be removed from ci.common. Given that our Gradle plugin also depends on this repo, having a dependency on a Maven artifact does not make sense. 

I will open a PR to remove it. The only classes we were utilizing were `DefaultArtifactVersion` and `ComparableVersion` to compare versions. We can do that in a different way.
