### ISSUE TITLE
Support variables in server.xml include location

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/ci.common#53]
server.xml can have an `<include location="...">` where it includes another xml file.  The location string can have a variable.  See https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_includes.html

When installing features from the server.xml and the included xmls, resolve the variables in the location strings.

**Comment by klieber** [comment]
@ericglau I need this feature as well.  I just opened #75 with a fix.
